apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-recommendation
  template:
    metadata:
      labels:
        app: realtime-recommendation
    spec:
      containers:
      - name: realtime-recommendation
        image: your-dockerhub-username/clickstream-analytics
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_DB
          value: "clickstream_db"
        - name: POSTGRES_USER
          value: "your_username"
        - name: POSTGRES_PASSWORD
          value: "your_password"
        command: ["python", "scripts/realtime_recommendation.py"]
